---
title: "20180123 - Friend or Foe"
author: "Evan L. Ray, adapted from Allan Rossman and Beth Chance"
date: "Janary 23, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Do children who are less than a year old recognize the difference between nice, friendly behavior as
opposed to mean, unhelpful behavior? Do they make choices based on such behavior? In a
study reported in the November 2007 issue of Nature, researchers investigated whether infants
take into account an individual's actions towards others in evaluating that individual as appealing
or aversive (Hamlin, Wynn, and Bloom, 2007).

In one component of the study, 10-month-old infants were shown a "climber" character
(a piece of wood with "google" eyes glued onto it) that
could not make it up a hill in two tries. Then they were alternately shown two scenarios for the
climber's next try, one where the climber was pushed to the top of the hill by another character
("friend") and one where the climber was pushed back down the hill by another character
("foe"). The infant was alternately shown these two scenarios several times. Then the child was
presented with both pieces of wood (representing the friend and the foe) and asked to pick one to
play with. Videos of this study are available at websites for the UBC Center for Infant Cognition Lab (<http://cic.psych.ubc.ca/example-stimuli/>) and the Yale Infant Cognition Center (<https://campuspress.yale.edu/infantlab/>).

### Objectives

This lab will introduce you to 3 Big Ideas that we'll come back to throughout this class:

 1. The importance of *experimental design*
 
 1. We can quantify *random variability*
 
 1. We can quantify the *strength of evidence* an experiment provides

Along the way, we'll also get a first look at `R`, the statistical programming language we'll use in this class.

### Evaluation

You will not be turning this lab in for a grade.

## Section 1: Introducing the Study

#### a) Identify the *observational units* and the *variables* in this study.  Is each variable categorical or quantitative?

The **observational unit** is the person or thing whose characteristics we measure in a study.  Depending on the context, an observational unit may also be referred to as a *case*, *respondent*, *subject*, or *participant*.

The **variables** are the characteristics recorded about each observational unit.  A **categorical** variable is a variable that identifies which of two or more different groups or categories each observational unit falls into -- for example, eye color could be viewed as a categorical variable.  A **quantitative** variable is a variable that is a number -- for example, height is a quantitative variable.

\vspace{4cm}

\newpage

#### b) The Methodology section states that for the 10-month-olds, the climber was a yellow triangle; helper and hinderer were a red square and a blue circle.  Which of the square and the circle was the helper and which was the hinderer was determined randomly for each baby.  Also randomized were which event (helping or hindering) they observed first and the positions of helper and hinderer when presented to the infants (on left or right). Why are these important considerations?

\vspace{4cm}

#### c) Researchers found that 14 of the 16 infants in the study selected the nice toy. Suggest two possible explanations for this result that the researchers observed.

\vspace{4cm}

#### d) Suppose for the moment that the researchers' conjecture is wrong, and infants actually have no preference for either type of toy. Would it be possible to have obtained a result as extreme as the researchers found?

\vspace{4cm}

#### e) If infants have no preference, how many of the 16 would you have expected to select the nice toy? Would you always expect to see that many of the 16 infants select the nice toy? How many of the 16 infants would have to select the nice toy in order for you to be fairly well convinced that the researchers' conjecture is correct, that infants really do have a tendency to prefer the nice toy? Explain.

\vspace{4cm}

#### f) In your judgment, how many infants, out of the 16, would have to select the nice toy in order for you to be fairly well convinced that the researchers' conjecture is correct, that infants really do have a tendency to prefer the nice toy? Explain.

\vspace{4cm}

## Section 2: A Simulation Study

The key question here is what results could reasonably occur under the assumption that infants actually have no preference. (We will call this assumption of no genuine preference the null model or null hypothesis.)  We will answer this question with by simulating (artificially re-creating) the selection process of 16 infants over and over, assuming that infants actually have no genuine preference.

#### g) Flip a coin 16 times. Record the number of heads that you obtain, which represents the number of your 16 hypothetical infants who choose the nice toy.

\vspace{4cm}

#### h) Combine your simulation results with your classmates. Produce a well-labeled dotplot. 

\vspace{1cm}

#### i) Where is the distribution of number of heads in 16 tosses centered? Explain why this makes sense.

\vspace{4cm}

#### j) Looking at this dotplot, does it seem that the result obtained by the researchers would have been surprising if in fact the infants had no preference? What does this suggest about whether the researchers' result provides much evidence that the infants do genuinely prefer the nice toy? Explain.

\vspace{4cm}

\newpage

## Section 3: Automating the Simulation using `R`

We really need to simulate this random selection process hundreds, preferably thousands of times. This would be very tedious and time-consuming with coins, so we'll turn to technology.  At this point, you'll need to register for our course on gryd.us.  This is a website where you can run R code, and the next few steps of the lab are there.  There's a registration link on our course website at [http://www.evanlray.com/stat140_s2018/schedule.html](http://www.evanlray.com/stat140_s2018/schedule.html).

#### k) Describe the shape of the histogram, and comment on whether it is centered where you expected.  Based on your simulation results, would you say that it would be very surprising, if infants actually have no genuine preference, that 14 out of 16 infants in the study would have chosen the nice toy just by chance? Explain.

\vspace{4cm}

#### l) Report how many of your 1000 repetitions produced 14 or more infants choosing the friend toy. Also determine the proportion of these 1000 repetitions that produced such an extreme result.

\vspace{4cm}

This proportion is called an approximate p-value. A p-value is the probability of obtaining a
result as extreme as the one observed, assuming that there is no genuine preference/difference.
A small p-value casts doubt on the null model/hypothesis used to perform the calculation (in
this case, that infants have no genuine preference).

* A p-value of .10 or less is generally considered to be some evidence against the
null model/hypothesis.
* A p-value of .05 or less is generally considered to be fairly strong evidence
against the null model/hypothesis.
* A p-value of .01 or less is generally considered to be very strong evidence against
the null model/hypothesis.
* A p-value of .001 or less is generally considered to be extremely strong evidence
against the null model/hypothesis.

#### m) Is the proportion you got in part o) small enough to consider the actual result obtained by the researchers surprising, assuming the null model that infants have no preference and so choose blindly between the two toys?
 
\vspace{2cm}

#### n) In light of your answers to the previous two questions, would you say that the experimental data obtained by the researchers provide strong evidence that infants in general have a genuine preference for the friend toy over the foe toy? Explain the reasoning process behind your answer.

\vspace{4cm}

#### o) In a follow-up study, the researchers repeated this protocol but without the googly eyes on the helper. In this study, they found that 10 of the 16 infants chose the helper toy. How does this change your p-value and conclusions? Use your earlier simulation results but explain what you are doing differently now to find the approximate p-value.  Explain why your answers make intuitive sense. Explain how this result contributes to the theory that infants are reacting to the social interaction of the toys.
