---
title: "Homework"
---

+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
| Assignment # | Description                                   | Due Date  | Value | Solutions                                |
+==============+===============================================+===========+=======+==========================================+
|    1         | 4 sections from the "Intro to R" course on    | 1/29/2018 |  0.5  |       N/A                                |
|              | Data Camp. Graded for completion only.        |           |       |                                          |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    2         | "Data Wrangling" chapter from the "Intro to   | 1/30/2018 |  0.25 |       N/A                                |
|              | the Tidyverse" course on Data Camp.           |           |       |                                          |
|              | Graded for completion only.                   |           |       |                                          |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    3         | "Data Visualization" and "Types of            | 2/1/2018  |  0.5  |       N/A                                |
|              | Visualizations" chapters from the "Intro to   |           |       |                                          |
|              | the Tidyverse" course on Data Camp.           |           |       |                                          |
|              | Graded for completion only.                   |           |       |                                          |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    4         | "Grouping and Summarizing"                    | 2/8/2018  |  0.25 |       N/A                                |
|              | chapter from the "Intro to                    |           |       |                                          |
|              | the Tidyverse" course on Data Camp.           |           |       |                                          |
|              | Graded for completion only.                   |           |       |                                          |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    5         | Wrap-up of Chapters 1 -- 4; assigned on Gryd. | 2/13/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    6         | Chapters 1 -- 4 and 6; assigned on Gryd.      | 2/20/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    7         | Chapters 11 -- 12; assigned on Gryd.          | 2/29/2018 |  0.5  |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    8         | Chapters 13 -- 14; assigned on Gryd.          | 3/9/2018  |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    9         | Chapters 15 -- 19; assigned on Gryd.          | 3/27/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    10        | Chapters 17, 20; assigned on Gryd.            | 4/03/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    11        | Chapter 20; assigned on Gryd.                 | 4/10/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    12        | Chapter 20; assigned on Gryd.                 | 4/17/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    13        | Chapters 7, 8, 25; assigned on Gryd.          | 4/24/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
|    14        | Chapters ?; assigned on Gryd.                 | 4/30/2018 |  1    |       N/A                                |
+--------------+-----------------------------------------------+-----------+-------+------------------------------------------+
