---
title: "Introduction to Statistics"
---

**Instructor:** Evan Ray

**Email:** eray@mtholyoke.edu

**Office:** Clapp 404C

**Office Hours:** Regularly scheduled office hours Mondays 4-5pm and Fridays 2-3pm.  These are times I guarantee I will be in my office and available, but that should **not** be interpreted as indicating that these are the only times I'm willing to meet.  Please do not hesitate to contact me to set up appointments for additional office hours at any time!!

**Evening Group Work**: We have scheduled rooms for evening group work, with TAs available to help with questions, on **Mondays, Tuesdays, Wednesdays, and Thursdays from 7 -- 9 pm**.  These sessions will meet in **Clapp 401**.  The TA's on Mondays and Wednesdays will be specifically prepared to help with questions related to what our section is working on, but the TAs on Tuesdays and Thursdays will also be able to answer general questions about R and statistics.

**Piazza:** We have a Piazza page at [https://piazza.com/mtholyoke/spring2018/stat140](https://piazza.com/mtholyoke/spring2018/stat140).  You can ask and answer questions there, anonymously if you want, and everyone in the class will be able to see and contribute to the answers.

**Syllabus:** [pdf](syllabus/syllabus_stat_140.pdf)

Please use the navigation menu above to go to the schedule, homework assignments, and materials related to quizzes and exams.
