---
title: "Schedule"
---

**Click on the text like "Week 1: Jan 22 -- 26" to expand or collapse the items we covered in that week.**

I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
  sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Jan 22 -- 26",
"Chapter 1: Observational Units, Categorical and Quantitative Variables

#### Tue, Jan 23

 * **In class**, we will work on:
    * Introductory lab: friend or foe? [pdf](lecture/20180123_friend_or_foe/20180123_friend_or_foe.pdf)
    * Here's a link to sign up for our class at gryd.us (this is the site where we will use R, you will need to do this to complete the lab): [https://beta.gryd.us/course/WNqfkUCNPkv2u3DBBWjnvh/register/](https://beta.gryd.us/course/WNqfkUCNPkv2u3DBBWjnvh/register/)

#### Thu, Jan 25
 * **Before class**, please do the following:
    * **Fill out** a brief pre-course [questionairre](https://goo.gl/forms/uaQwDv6PFuoT0PD43)
    * **Fill out** this poll about when my office hours should be held: [http://whenisgood.net/2r7jg27](http://whenisgood.net/2r7jg27)
    * Sign up for our class at gryd.us if you didn't already (this is the site where we will use R): [https://beta.gryd.us/course/WNqfkUCNPkv2u3DBBWjnvh/register/](https://beta.gryd.us/course/WNqfkUCNPkv2u3DBBWjnvh/register/)
    * Sign up for our class at Piazza (anonymous question and answer forum): [https://piazza.com/mtholyoke/spring2018/stat140](https://piazza.com/mtholyoke/spring2018/stat140)
    * **Reading**: Read Chapter 1 of Stats: Data and Models 4th edition, or Chapter 2 of the 3rd edition
    * **Homework 1**: Complete 4 [DataCamp](https://www.datacamp.com) chapters on Introduction to R.  You will get an email by the end of the day on Jan 23 inviting you to join our class organization with an assignment pointing you to the specific chapters to do.  You should **feel free to work on this in groups** -- but please **each complete your own copy of this assignment**!  Your grade on this assignment is only for completion, not correctness.  If you get stuck, post a message on Piazza!  I don't expect you to remember everything or feel like an expert at it; that's what the rest of the class is for!  This is just a first introduction.
* **In class**, we will do the following:
    * Introduction to R and Categorical Data lab on Gryd.
    * If Gryd fails, we'll look at an example from Chapter 2.

#### Fri, Jan 26
 * **Before class**, please do the following:
    * **Reading**: Read Chapter 2 of Stats: Data and Models 4th edition, or Chapter 3 of the 3rd edition
    * Finish **Homework 1** if you didn't already
 * **In class**, we will do the following:
    * Start a lab about Relationships Between Multiple Categorical Variables on Gryd
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Jan 29 -- Feb 2",
"

#### Tue, Jan 30
 * **Before class**, please do the following:
    * Finish **Homework 1** (due Monday Jan 29) and **Homework 2** (due Tuesday Jan 30; also on Data Camp)
 * **In class**, we will do the following:
    * Finish the lab about Relationships Between Multiple Categorical Variables that we started on Fri, Jan 26
    * Briefly, review of the most important things in R so far: [pdf](lecture/20180130_wrangling/20180130_r_so_far.pdf)

#### Thu, Feb 1
 * **Before class**, please do the following:
    * Finish **Homework 3** (due Thursday Feb 1)
    * **Reading**:
      * Read the first part of Section 3.1 (just the part about Histograms, no stem and leaf displays or dot plots), Section 3.2, all of Chapter 4, and Section 6.1 of Stats: Data and Models 4th edition, or
      * The parts of Chapter 4 with headings 'Histograms' and 'The Shape of a Distribution', all of Chapter 5, and the first two parts of Chapter 7 (with headings 'Looking at Scatterplots' and 'Roles for Variables') of the 3rd edition
 * **In class**, we will do the following:
    * Lab about **data wrangling** in R on Gryd

#### Fri, Feb 2
 * **Before class**, please do the following:
    * No new assignments
 * Overview of data visualization with the Grammar of Graphics: [pdf](lecture/20180202_visualization/20180202_visualization.pdf)
 * Lab about **data visualization** in R on Gryd
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Feb 5 -- 9",
"

#### Tue, Feb 6
 * **Before class**, please do the following:
    * Nothing new.
 * **In Class**, we will do the following:
    * Finish off **data visualization**

#### Thu, Feb 8
 * **Before class**, please do the following:
    * Homework 4 is due today
    * **Reading**: 
      * Sections 3.3 through 3.8 (you should have already read Section 3.2 and parts of 3.1) of the 4th edition, or
      * The parts of Chapter 4 that you didn't read yet, in the 3rd edition.
 * **In class**, we will do the following:
    * Summaries of quantitative variables: [pdf](lecture/20180207_summarize/20180207_summarize.pdf)

#### Fri, Feb 9
 * **Before class**, please do the following:
    * **Reading**: 
      * Sections 6.2, 6.3, and 6.4 of the 4th edition  -- but not the sections about Kendall's Tau or Spearman's Rho
      * The parts of chapter 7 you didn't read yet, in the 3rd edition -- but not the sections about Kendall's Tau or Spearman's Rho
 * **In class**, we will do the following:
    * Continue lab from Thursday Feb 9
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", FALSE, "Week 4: Feb 12 -- 16",
"

#### Tue, Feb 13
 * **Before class**, please do the following:
    * **Homework 5** is due today; on Gryd
 * **In class**, we will do the following:
    * Overview of scatter plots and correlation: [pdf](lecture/20180213_correlation/20180213_correlation_summary.pdf)
    * Example of scatter plots and correlation as a class: [pdf](lecture/20180213_correlation/20180213_correlation.pdf)
    * Lab 6 on Gryd
    * If time, guess the correlation: [pdf](lecture/20180213_correlation/20180213_plots_correlation.pdf)

#### Thu, Feb 15
 * **Before class**, please do the following:
    * **Reading**: Chapter 11 of SDM 4th edition or Chapter 12 of SDM 3rd edition
    * **Finish lab** from Tuesday if you didn't finish in class; solutions will be posted.
    * Start on **Homework 6**
 * **In class**, we will do the following:
    * Review ideas from Chapter 11
    * Lab 7 on Gryd: sampling

#### Fri, Feb 16
 * **Before class**, please do the following:
    * **Reading**: Chapter 12 of SDM 4th edition or Chapter 13 of SDM 3rd edition
 * **In class**, we will do the following:
    * Overview of Chapter 12: [pdf](lecture/20180216_experimental_design/20180216_experiments_observational_summary.pdf)
    * Look at some examples of published articles.  Blank:  [pdf](lecture/20180216_experimental_design/20180216_experiments_observational.pdf) Solutions: [pdf](lecture/20180216_experimental_design/20180216_experiments_observational_solutions.pdf)
    * Article 1: peanut allergies [pdf](lecture/20180216_experimental_design/Du_Toit_et_al_-_peanut_consumption.pdf)
    * Article 2: colds and meditation [pdf](lecture/20180216_experimental_design/colds-and-meditation_Annals-Family-Medicine_12.pdf)
    * Article 3: coffee drinking and mortality [pdf](lecture/20180216_experimental_design/coffee-drinking-and-mortality_NEJM-12.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", FALSE, "Week 5: Feb 19 -- 23",
"

#### Tue, Feb 20
 * **Before class**, please do the following:
    * **Homework 6** is due today; on Gryd
 * **In class**, we will do the following:
    * **Example** connecting course ideas together and introducing probability: taste tests.  [pdf](lecture/20180220_tasting/20180220_tasting.pdf)

#### Thu, Feb 22
 * **In class**, we will do the following:
    * **Quiz** on material from HW 5
    * Start on probability
    * Rules for probability: [pdf](lecture/20180222_probability/20180222_probability.pdf)
    * First examples with probability: [pdf](lecture/20180222_probability/20180222_probability_examples.pdf)

#### Fri, Feb 23
 * **In class**, we will do the following:
    * Probability continued
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", FALSE, "Week 6: Feb 26 -- Mar 2",
"

#### Tue, Feb 27
 * **In class**, we will do the following:
    * **Quiz** on material from HW 6
    * Examples of conditional probability, probability of A and B: [pdf][lecture/20180226_probability/20180227_probability_examples_conditional_and_and.pdf]

#### Thu, Mar 1
 * **Before class**, please do the following:
    * **Homework 7** due today.
 * **In class**, we will do the following:
    * Examples of Probability of A and B, posted Feb 27.
    * Start on examples of Bayes' Rule: [pdf](lecture/20180226_probability/20180227_probability_examples_bayes.pdf); Solutions: [pdf](lecture/20180226_probability/20180227_probability_examples_bayes_solutions.pdf)

#### Fri, Mar 2
 * **In class**, we will do the following:
    * Continue working on examples of Bayes' Rule; examples and solutions posted for Mar 1.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", FALSE, "Week 7: Mar 5 -- 9",
"
 * **Midterm 1** due Friday, Mar 9 at 5pm; covers material from Chapters 1 -- 4, 6, 11, and 12 (up through HW 7).  Take home.

#### Tue, Mar 6
 * **Before class**, please do the following:
    * Read Sections 15.1 and 15.2, 16.1, 16.2, and 16.3 in SDM4; In SDM3, the first few sections of Chapter 16 (up to but not including \"More About Means and Variances\"), and the first few sections of Chapter 17 (up to but not including \"The Normal Model to the Rescue!\")
 * **In class**, we will do the following:
    * **Quiz** on material from HW 7
    * Lecture covering the highlights from Chapters 15 and 16: [pdf](lecture/20180306_binomial/20180306_binomial.pdf)
    * Lab 9 about the Binomial distribution on Gryd

#### Thu, Mar 8
 * **Before class**, please do the following:
    * If you want, you can skim Chapters 18 and 19 of SDM4; Chapters 19 and 20 of SDM3.  We will use a different approach to this material than the textbook, and will not go into as much depth as the text, but this reading may still be helpful to get some of the ideas.
 * **In class**, we will do the following:
    * Short overview of hypothesis tests and confidence intervals for proportions
    * Lab 10 on Gryd

#### Fri, Mar 9
 * **In class**, we will do the following:
    * Finish lab 10 on Gryd.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", FALSE, "Week 8: Mar 12 -- 16",
"
#### Spring Break: safe travels!
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", FALSE, "Week 9: Mar 19 -- 23",
"

#### Tue, Mar 20
 * **In class**, we will do the following:
    * Review/wrap-up of M&M's lab: [pdf](lecture/20180320_p_inference/20180320_p_inference.pdf)
    * Lab 11 on Gryd: interpretation of confidence intervals

#### Thu, Mar 22
 * **In class**, we will do the following:
    * **Quiz** on independent and disjoint events.  Be able to define independent and disjoint events, and to check whether two events are independent or disjoint.  Sample quiz and solutions will be posted on the Exams page on the course website.
    * Wrap up inference for a population proportion: [pdf](lecture/20180322_p_inference_examples/20180322_p_inference_examples.pdf)
    * Briefly, discuss the ASA statement on p-values: [pdf](lecture/20180322_p_inference_examples/The_ASA_Statement_on_p_values_-_Context_Process_and_Purpose_highlighted.pdf)

#### Fri, Mar 23
 * **Before class**, please do the following:
    * **Please read:** Sections 5.3, 17.3, 17.4, and 17.5 of SDM4; or in SDM3, the section of Chapter 6 called 'When is a z-score BIG', and the sections of Chapter 18 from 'What About Quantitative Data' on.
 * **In class**, we will do the following:
    * Start to think about the sampling distribution of the sample mean.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", TRUE, "Week 10: Mar 26 -- 30",
"

#### Tue, Mar 27
 * **In class**, we will do the following:
    * Introduction/example of inference for a population mean [pdf](lecture/20180327_mean_sampling_distribution/20180327_mean_sampling_distribution.pdf)
    * Start Lab 13 on Gryd

#### Thu, Mar 29
 * **In class**, we will do the following:
    * Discuss the sampling distribution of the sample mean and the central limit theorem [pdf](lecture/20180329_clt/20180329_clt.pdf)
    * Continue Lab 13 on Gryd, start Lab 14 on Gryd

#### Fri, Mar 30
 * **In class**, we will do the following:
    * Continue Labs 13 and 14 on Gryd
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", TRUE, "Week 11: Apr 2 -- 6",
"

#### Tue, Apr 3
 * **Before class**, please do the following:
    * **Homework 10** is due today!
    * If you haven't already, **please read:** Sections 5.3, 17.3, 17.4, and 17.5 of SDM4; or in SDM3, the section of Chapter 6 called 'When is a z-score BIG', and the sections of Chapter 18 from 'What About Quantitative Data' on.
    * Additionally, **please read** Chapter 20 of SDM4, Chapter 23 of SDM3
 * **In class**, we will do the following:
    * Wrap Up/Summarize the sampling distribution of the sample mean; lab 14
    * Start connecting this to mechanics of inference for a population mean - what's going on behind the scenes?
    * Handout for the week: [pdf](lecture/20180403_z_score_t_test/20180403_z_score_t_test.pdf)
    * Solutions for examples 5 and 6 in handout: [pdf](lecture/20180403_z_score_t_test/20180403_z_score_t_test_solutions.pdf)

#### Thu, Apr 5
 * **In class**, we will do the following:
    * **Quiz** on Homework 9
    * Continue looking at the mechanics of inference for a population mean - what's going on behind the scenes?

#### Fri, Apr 6
 * **In class**, we will do the following:
    * Wrap Up looking at the mechanics of inference for a population mean - what's going on behind the scenes?
    * New handout: [pdf](lecture/20180406_t_test/20180406_t_test.pdf)
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", TRUE, "Week 12: Apr 9 -- 13",
"
**Midterm 2**: Material from homeworks 8, 9, and 10 - take home.

#### Tue, Apr 10

#### Thu, Apr 12

#### Fri, Apr 13
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", TRUE, "Week 13: Apr 16 -- 20",
"

#### Tue, Apr 17

#### Thu, Apr 19

#### Fri, Apr 20
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", TRUE, "Week 14: Apr 23 -- 27",
"

#### Tue, Apr 24

#### Thu, Apr 26

#### Fri, Apr 27
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: Thu, May 3 at 7pm -- Mon, May 7 at noon",
"We will have a cumulative final exam.
"
  )
```
